### ISSUE TITLE
Randomly starts playing

### ISSUE THREAD

**Issue by muddro1** [mattttvaughn/chronicle#24] opened 2022-01-12 13:28 UTC
Not sure what is happening. I'm on a pixel 5 with Android 12. Every once in a while chronicle will just start playing. Please let me know if there is anything I can provide.

**Comment by pmayeur** [comment] 2022-01-13 14:17
I also get this often. Sometimes it is if paused when going from wifi to data or vice versa

**Comment by runningslow81** [comment] 2022-01-24 03:52
This happens to me as well. I have noticed it most when my phone transitions from mobile data to wifi.

**Comment by pmayeur** [comment] 2022-02-03 22:13
I can reproduce 100%

Open app and play book.
Pause book
Turn on airplane mode
Turn off airplane mode



Pixel 6
Android 12

**Comment by pmayeur** [comment] 2022-02-22 21:50
If you set "Refresh Frequency" to 'Manual' this issue doesn't happen.

So it's a combination of refresh and losing connection

**Comment by oucil** [comment] 2022-03-04 14:15
Seems like a couple Pixel comments here, so I'll add mine to the pile, I'm on a Pixel 3, Android 12, same issue, and same circumstances, often when changing from cell to wifi, though I don't think I've noticed it when going from wifi to cell, but that could just be the circumstances as I'm often wearing a headset or going into car with BT when I'm headed out.

**Comment by Odinau** [comment] 2022-03-18 04:25
I have the same problem but not using a pixel but a Samsung Galaxy S22 with Android 12. I often re open the app and am now hours ahead of what I was last time I paused play. It doesn't matter if I pause and leave the app in the background or close the app completely. Restarting the phone also does not stop auto random playing.

**Comment by mattttvaughn** [comment] 2022-03-19 01:20
Looks like it was an Android 12+ issue. #45 should resolve this. Give it a run, I'll close this out tomorrow unless anyone reports continued issues

https://github.com/mattttvaughn/chronicle/releases/tag/0.51.3

**Comment by Odinau** [comment] 2022-03-19 01:47
Thank you. Will give it a whirl and report if not resolved.

**Closed as completed** 2022-03-20 18:10 UTC
Labels: bug
